##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# 2009.02 - Currently managed by  JongMinKim <jm45.kim@samsung.com> , SungHwanYun <sunghwan.yun@samsung.com>
##############################################################################
# VERSION&DATE	: Version 1.00	2009/02
##############################################################################


obj-$(CONFIG_J4FS) := j4fs_kernel.o llid_kernel.o fsd_common.o

